### ISSUE TITLE
RFSoC_OPFB v 2.0 issue

### ISSUE THREAD

**Issue by cable436** [MazinLab/RFSoC_OPFB#2]
Thanks for providing the open source code. It has been a big help but I am having an issue with the newer v 2.0. I am able to run the earlier v 1.0 on my ZCU111 without any problems. But with the newer version I am running into some problems. I installed the bit file and hwh file for v2.0 onto Jupyter and was able to load the bitstream succesfully on to my ZCU111 board.

However when I try to run the following code from the section in opfb_demo.ipynb my system will 'hang'. 
**if ol.dac_table.register_map.run.run:
    ol.dac_table.stop()
ol.dac_table.replay(dactable['iq'],fpgen='simple')**

Looking into this more I found that it seems to be hanging when it is trying to R/W on the dac_table IP registers. I noticed that the dac_table ap_clk is connected up to a 256 MHz clock from the clk_dac0 output on the rfdc. For quick testing I connected the dac_table ap_clk to the pl_clk (at 100 MHz) on the zynq ultrascale+ processor and I was then able to R/W these registers. Could it be some cross-domain clocking issues?

Have you ever seen these type of issues with the system hanging because of R/W issues? I have been looking at this for about a week trying to figure out how to resolve the issue. Thanks for any assistance!

**Comment by cable436** [comment]
Looks like that not setting up the internal clock on the ZCU111 was my issue. In the overlay configure method changed the **clocks** option to True in opfb_demo.ipynb file.

**Comment by JennySmith888** [comment]
This is a good catch. I'll change the default notebook to program the clocks.
